services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            # Xdebug desabilitado em produção
            XDEBUG_MODE: 'off'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/up"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    redis:
        image: 'redis:alpine'
        restart: unless-stopped
        # Redis não exposto ao host em produção - apenas na rede interna
        # ports:
        #     - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3

networks:
    sail:
        driver: bridge

volumes:
    sail-redis:
        driver: local
