<?php

namespace Tests\Feature;

use App\Models\Orcamento;
use App\Models\OrcamentoItem;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PuppeteerOrcamentoPdfTest extends TestCase
{
    use RefreshDatabase;

    public function test_puppeteer_generates_pdf_file()
    {
        // Preparar dados
        $user = User::factory()->create();
        $orc = Orcamento::factory()->create([
            'valor_total' => 500.00,
            'forma_pagamento' => 'pix',
        ]);

        // Criar um item válido
        $orc->itens()->create([
            'descricao_item' => 'Teste Item',
            'unidade_medida' => 'm2',
            'quantidade' => 2,
            'valor_unitario' => 250.00,
        ]);
        $orc->calcularTotal();
        $orc->save();

        // Renderizar HTML via comando artisan
        $this->artisan('stofgard:render-orcamento-html', ['orcamentoId' => $orc->id])->assertExitCode(0);

        $htmlPath = storage_path("debug/orcamento-{$orc->id}.html");
        $pdfPath = storage_path("debug/orcamento-{$orc->id}-puppeteer.pdf");

        $this->assertFileExists($htmlPath);

        // Executar script Node (se disponível)
        $node = env('NODE_BINARY', 'node');
        $script = base_path('scripts/generate-pdf.js');

        // Skip the test when Node is not available or not a real Node binary
        try {
            $versionProc = new \Symfony\Component\Process\Process([$node, '--version']);
            $versionProc->setTimeout(10);
            $versionProc->run();
            $versionOut = trim($versionProc->getOutput() ?: $versionProc->getErrorOutput());
            if (! preg_match('/^v\d+\./', $versionOut)) {
                $this->markTestSkipped('Node binary not found or not a node executable; skipping Puppeteer integration test.');
            }
        } catch (\Throwable $e) {
            $this->markTestSkipped('Node binary not found; skipping Puppeteer integration test.');
        }

        // Use Symfony Process to handle paths with spaces and properly capture output
        $process = new \Symfony\Component\Process\Process([$node, $script, $htmlPath, $pdfPath]);
        $process->setTimeout(120);
        $process->run();

        $this->assertTrue($process->isSuccessful(), 'Node script should run successfully: ' . $process->getErrorOutput());
        $this->assertFileExists($pdfPath, 'PDF must be generated by Puppeteer');
        $this->assertGreaterThan(5000, filesize($pdfPath), 'PDF should be > 5KB');

        // Cleanup
        @unlink($htmlPath);
        @unlink($pdfPath);
    }
}
