[program:stofgard-worker]
process_name=%(program_name)s_%(process_num)02d
command=/bin/sh -c "docker exec ${STOFGARD_APP_CONTAINER:-stofgard-app-final-laravel.test-1} php artisan queue:work ${QUEUE_CONNECTION:-database} --queue=${QUEUE_NAMES:-high,default,low} --sleep=1 --tries=3 --max-time=3600"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/stofgard-worker.log
stopwaitsecs=3600
