server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /login {
        return 301 https://app.autonomia.app.br/login;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
